modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
	modId="uniqueutil"
	version="${version}"
	displayName="Unique Util Enchantments"
	credits="Thanks Xaikii for the Mod Design, Thanks to Speiger for the Code"
	authors="Speiger, Xaikii"
	description='''
	A Set of Unique Utility Enchantments
	'''
	[[dependencies.uniqueutil]]
		modId="uniquebase"
		mandatory=true
		versionRange="[${base_version},)"
		ordering="BEFORE"
		side="BOTH"