modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
	modId="uniquebattle"
	version="${version}"
	displayName="Unique Battle Enchantments"
	credits="Thanks Xaikii for the Mod Design, Thanks to Speiger for the Code"
	authors="Speiger, Xaikii"
	description='''
	A Set of Unique Battle Enchantments
	'''
	[[dependencies.uniquebattle]]
		modId="uniquebase"
		mandatory=true
		versionRange="[${base_version},)"
		ordering="BEFORE"
		side="BOTH"