modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
[[mods]]
	modId="uniquebase"
	version="${version}"
	displayName="Unique Enchantments Base"
	credits="Thanks Xaikii for the Mod Design, Thanks to Speiger for the Code"
	authors="Speiger, Xaikii"
	description='''
	A Base Library for Unique Enchantments Mods
	'''